# Generated by Django 5.0.4 on 2024-04-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usom_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainip",
            name="similar_iocs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domainip",
            name="whois_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
