# Generated by Django 5.0.4 on 2024-04-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usom_app", "0002_domainip_similar_iocs_domainip_whois_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainip",
            name="domain",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="domainip",
            name="ip",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
